In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
print(a)

[ 1.46627363 -0.88371771 -0.46608936 -0.34062858 -0.77506294]


In [3]:
print(a.T)

[ 1.46627363 -0.88371771 -0.46608936 -0.34062858 -0.77506294]


In [4]:
print(a@a.T)

3.8649050265428126


In [5]:
a = np.random.randn(5,1)
print(a)

[[-0.80048132]
 [-1.05068974]
 [ 0.38398914]
 [-1.41268982]
 [ 0.06303844]]


In [6]:
print(a.T)

[[-0.80048132 -1.05068974  0.38398914 -1.41268982  0.06303844]]


In [7]:
print(a@a.T)

[[ 0.64077034  0.84105751 -0.30737613  1.13083181 -0.05046109]
 [ 0.84105751  1.10394893 -0.40345345  1.48429869 -0.06623384]
 [-0.30737613 -0.40345345  0.14744766 -0.54245755  0.02420608]
 [ 1.13083181  1.48429869 -0.54245755  1.99569252 -0.08905376]
 [-0.05046109 -0.06623384  0.02420608 -0.08905376  0.00397384]]


In [10]:
assert(a.shape==(5,1))

In [11]:
assert(a.shape==(5,2))

AssertionError: 